language: objective-c
osx_image: xcode8
xcode_workspace: hachat.xcworkspace 
xcode_scheme: hachat
xcode_sdk: iphoneos10.0
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool